### ISSUE TITLE
文字消息提醒频道

### ISSUE THREAD

**Issue by Amber77711** [NukoOoOoOoO/RankSSpawnHelper-Extra#1]
功能-自动退本(青魔消debuff)
请问可以让它的文字消息提醒跟随dalamud设置中的通用聊天频道一致吗？不要强制显示在Debug频道
“[自动退本] 职业只能是青魔”
“[自动退本] 该功能只能在假火神(伊芙利特讨伐战)用”

**Comment by Nukoooo** [comment]
6.5的时候会重写整个插件,如果有需要的话可以自己 clone 下来然后把那段消息给删掉
